// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnRUaCaTKrVXlN5mGbTwEwyfBtwR0gV_Q',
    appId: '1:1024066824056:web:c1875af89d238325c54a8d',
    messagingSenderId: '1024066824056',
    projectId: 'saffronedgetest',
    authDomain: 'saffronedgetest.firebaseapp.com',
    storageBucket: 'saffronedgetest.firebasestorage.app',
    measurementId: 'G-Q9RQQS4H54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDswWev6AKItFjvj_NRjOdNjQ3U8iL0F98',
    appId: '1:1024066824056:android:65e601eac88195c5c54a8d',
    messagingSenderId: '1024066824056',
    projectId: 'saffronedgetest',
    storageBucket: 'saffronedgetest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF5j8u8FQT2KHg2iG4tZYZApp1Y-Clayk',
    appId: '1:1024066824056:ios:7ad034c37e93ca2fc54a8d',
    messagingSenderId: '1024066824056',
    projectId: 'saffronedgetest',
    storageBucket: 'saffronedgetest.firebasestorage.app',
    iosBundleId: 'com.example.saffronedgetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF5j8u8FQT2KHg2iG4tZYZApp1Y-Clayk',
    appId: '1:1024066824056:ios:7ad034c37e93ca2fc54a8d',
    messagingSenderId: '1024066824056',
    projectId: 'saffronedgetest',
    storageBucket: 'saffronedgetest.firebasestorage.app',
    iosBundleId: 'com.example.saffronedgetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnRUaCaTKrVXlN5mGbTwEwyfBtwR0gV_Q',
    appId: '1:1024066824056:web:a62a7085b0d25b82c54a8d',
    messagingSenderId: '1024066824056',
    projectId: 'saffronedgetest',
    authDomain: 'saffronedgetest.firebaseapp.com',
    storageBucket: 'saffronedgetest.firebasestorage.app',
    measurementId: 'G-LT6WX9K5SY',
  );
}
